services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./.tmp/database:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:${WP_VERSION}
    restart: always
    depends_on:
      - mysql
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: mysql:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: 1
    volumes:
      - "./.tmp/wordpress:/var/www/html"
      - "./docker/wordpress/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "./plugin:/var/www/html/wp-content/plugins/${WP_PLUGIN_NAME}"
      - "./theme:/var/www/html/wp-content/themes/${WP_THEME_NAME}"

  composer:
    image: composer:${COMPOSER_VERSION}
    container_name: composer
    working_dir: /app
    volumes:
      - ./:/app
    # entrypoint: [ "tail", "-f", "/dev/null" ]

  node:
    image: node:${NODE_VERSION}
    container_name: node
    working_dir: /app
    volumes:
      - ./:/app
    # entrypoint: [ "tail", "-f", "/dev/null" ]
